### ISSUE TITLE
Fertility Bug

### ISSUE THREAD

**Issue by DanielTurnquist** [MedievalSchwitters/Medieval#2]
problem: nobody ever becomes fertile

**Comment by TailsTyler** [comment]
im trying to push but  i get 

          On branch master
          Changes not staged for commit:
            (use "git add <file>..." to update what will be committed)
            (use "git restore <file>..." to discard changes in working directory)
            (commit or discard the untracked or modified content in submodules)
                  modified:   Medieval (modified content)
          
          no changes added to commit (use "git add" and/or "git commit -a")

even after i use

           git add .
